coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 0%
        base: auto
        # advanced
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
