global class DescribeTabSetResult {
	global String description;
	global String label;
	global String logourl;
	global String namespace;
	global Boolean selected;
	global List<Schema.DescribeTabResult> tabs;
	global String tabsetid;
	global String getDescription() { }
	global String getLabel() { }
	global String getLogoUrl() { }
	global String getNamespace() { }
	global String getTabSetId() { }
	global List<Schema.DescribeTabResult> getTabs() { }
	global Boolean isSelected() { }

}