global class RecordTypeInfo {
	global Boolean active;
	global Boolean available;
	global Boolean defaultrecordtypemapping;
	global String developername;
	global Boolean master;
	global String name;
	global Id recordtypeid;
	global String getDeveloperName() { }
	global String getName() { }
	global Id getRecordTypeId() { }
	global Boolean isActive() { }
	global Boolean isAvailable() { }
	global Boolean isDefaultRecordTypeMapping() { }
	global Boolean isMaster() { }

}