package sfdc.sfdx.scanner;

public enum EventKey {
  // ANY NEW VALUES ADDED TO THIS ENUM MUST HAVE A CORRESPONDING ENTRY IN 'messages/EventKeyTemplates.js'!
  WARNING_INVALID_CAT_SKIPPED("WARNING_INVALID_CAT_SKIPPED", 1),
  WARNING_INVALID_RULESET_SKIPPED("WARNING_INVALID_RULESET_SKIPPED", 1),
  WARNING_XML_DROPPED("WARNING_XML_DROPPED", 1),
  INFO_JAR_AND_XML_PROCESSED("INFO_JAR_AND_XML_PROCESSED", 2),
  ERROR_UNEXPECTED("ERROR_UNEXPECTED", 1),
  ERROR_INTERNAL_MAIN_INVALID_ARGUMENT("ERROR_INTERNAL_MAIN_INVALID_ARGUMENT", 1),
  ERROR_INTERNAL_JSON_WRITE_FAILED("ERROR_INTERNAL_JSON_WRITE_FAILED", 1),
  ERROR_INTERNAL_CLASSPATH_DOES_NOT_EXIST("ERROR_INTERNAL_CLASSPATH_DOES_NOT_EXIST", 1),
  ERROR_EXTERNAL_JAR_NOT_READABLE("ERROR_EXTERNAL_JAR_NOT_READABLE", 1),
  ERROR_EXTERNAL_DIR_NOT_READABLE("ERROR_EXTERNAL_DIR_NOT_READABLE", 1),
  ERROR_EXTERNAL_MULTIPLE_RULE_DESC("ERROR_EXTERNAL_MULTIPLE_RULE_DESC", 2),
  ERROR_EXTERNAL_RECURSION_LIMIT("ERROR_EXTERNAL_RECURSION_LIMIT", 2),
  ERROR_EXTERNAL_XML_NOT_READABLE("ERROR_EXTERNAL_XML_NOT_READABLE", 2),
  ERROR_EXTERNAL_XML_NOT_PARSABLE("ERROR_EXTERNAL_XML_NOT_PARSABLE", 2);

  String messageKey;
  int argCount;

  EventKey(String messageKey, int argCount) {
    this.messageKey = messageKey;
    this.argCount = argCount;
  }

  public int getArgCount() {
    return this.argCount;
  }
}
