public class fileA2 {



	public boolean doSomething() {
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		System.debug(LoggingLevel.ERROR, 'asdfasdfasdf');
		return false;
	}














	public void methodDeclaredAtLine20() {
	}






}
